name: Build & Publish CI/CD

on:
  push:
    tags:
      - '*'

jobs:
  build_test_publish_job:
    name: Build -> Test -> Publish to Maven Central
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
          cache-overwrite-existing: true
      
      - name: Decrypt secrets
        run: ./.github/scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build and test
        run: ./gradlew build --stacktrace
      
      - name: Publish to Maven Central
        run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache
