name: Build CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    branches: [ master ]

jobs:
  build_job:
    name: Build & Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
          cache-overwrite-existing: true
      
      - name: Decrypt secrets
        run: ./.github/scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build and run unit tests
        run: ./gradlew build --stacktrace